name: publish
on:
  push:
    tags:
      - 'v*'
      
jobs:
  publish-docker-image:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag:1}
          image=ghcr.io/${GITHUB_REPOSITORY}
          docker build . -t ${image}:${tag} -t ${image}:latest
          docker push ${image} --all-tags
          